### ISSUE TITLE
Add option for dynamically sized merged textures

### ISSUE THREAD

**Issue by TyOverby** [PistonDevelopers/texture_packer#22]
Now that we aren't copying the pixels into a backing buffer, it doesn't matter how big the resulting merged image is.  There should be an option to allow the merged image to get as large as it wants, but tries to stay as close to square as possible.

**Comment by simnalamburt** [comment]
Texture packing problem is basically 2-dimensional bin packing problem, and currently there's no good heuristic solution without its size limit. And practically you always have limits of texture's dimension to use it due to the limitation of the hardware; GPU or RAM.

If you make a *good* heuristic solution of the bin packing problem without the size limit, you'll probably get some PhD or something. If you reference some paper with a solution without the size limit, then we'll have some chance to implement it.
